apiVersion: v1
kind: Service
metadata:
  name: catalytics-core-service
  namespace: ${NAMESPACE}
  labels:
    app: catalytics-core
spec:
  selector:
    app: catalytics-core
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP